<template lang="pug">
p De lijsten op deze website zijn gebaseerd op de Tijdloze zoals die op de radio wordt uitgezonden en op de officiële VRT-website wordt gepubliceerd. In principe wordt de ranglijst volledig bepaald door de stemmen van de luisteraars, al heeft Studio Brussel nooit details vrijgegeven over de manier waarop de stemmen worden geteld en omgezet in een rangschikking. Evenmin maakt Studio Brussel normaal gezien details bekend over het totaal aantal stemmen dat werd uitgebracht, of over de precieze verdeling van de stemmen over de verschillende nummers.
p
  make-links(text="Sowieso zijn er door de jaren heen significante veranderingen gebeurd bij de manier waarop stemmen worden verzameld. In de beginjaren kon er enkel op papier worden gestemd, tegenwoordig gebeurd de stemming volledig online. Bij een online-stemming kan het stemgedrag beïnvloed worden door de manier waarop nummers tijdens het typen gevonden/gesuggereerd worden, een invloed die echter moeilijk te meten is. Bovendien zijn er in de loop der jaren nieuwe regels ingevoerd, zoals een miminale leeftijd voor nummers. Terwijl vroeger de hoogste nieuwkomers meestal heel recente nummers waren (van [Smells Like Teen Spirit] in 1991 tot [Sex on Fire] in 2009), eist Studio Brussel tegenwoordig dat een nummer minstens drie jaar oud moet zijn om in de lijst te mogen verschijnen.")
p
  make-links(text="Er zijn enkele gevallen bekend waarbij Studio Brussel na het tellen van de stemmen nog wijzigingen heeft aangebracht aan de lijst. Zo werden in 1998 alle stemmen met het nummer <em>Er staat een paard in de gang</em> van André van Duin op de eerste plaats ongeldig verklaard, nadat enkele grappenmakers massaal stemmen voor dit nummer hadden geronseld. In 2014 werd [Mia] van [Gorki], dat anders waarschijnlijk niet eens de top 20 had gehaald, door Studio Brussel op de eerste plaats gezet, nadat kort na het afsluiten van de stemming bekend werd dat zanger Luc De Vos was overleden. Had de stemweek na het overlijden van De Vos plaatsgevonden, dan was [Mia] hoogstwaarschijnlijk sowieso op de eerste plaats geëindigd.")
p
  make-links(text="De actie om <em>Er staat een paard in gang</em> in de Tijdloze van 1998 te krijgen, werd door Studio Brussel gedwarsboomd, maar er zijn andere campagnes geweest die de lijst wel beïnvloed hebben, en die zelfs expliciet door de VRT ondersteund werden. Zo was er in 2017 de actie, gedreven door dj Nadiem Shah, om [Africa] van [Toto] in de Tijdloze 100 te krijgen, wat ook lukte. In 2018 voerde RoSa vzw een grote campagne om meer vrouwelijke artiesten in de top 100 te krijgen, die ook successvol was.")
p
  make-links(text="De waarschijnlijkheid is groot dat Studio Brussel ook af en toe foutjes heeft gemaakt bij het tellen van de stemmen. Anders is het bijna niet te verklaren waarom [One;U2] van [U2] in 2015 uit de top 100 verdween, in tegenspraak met de vele stemmen die dit nummer had gekregen in een grote verzameling van gelekte stemmen. Ook het verdwijnen van [Exit Music (For a Film)] van [Radiohead] uit de volledige countdown in 2024 is niet geloofwaardig, aangezien het nummer al vele jaren stabiel rond positie 300 stond en er met de vele andere nummers van Radiohead niets gelijkaardigs gebeurde. Wij doen geen poging om zulke vermoedelijke foutjes in onze databank te corrigeren, ook omdat we sowieso geen betere gegevens ter beschikking hebben.")
p
  make-links(text="Er waren ook al meerdere edities van de Tijdloze waar eenzelfde nummer meermaals in de lijst stond. [Hallelujah;Jeff Buckley] van [Jeff Buckley] en [Sunday Bloody Sunday] van [U2] stonden in 2019 zowel met de studio-versie als met een live-versie in de countdown. Hetzelfde gebeurde in 2023 met [Lippy Kids] von [Elbow]. Aangezien zulke gevallen een uitzondering blijven, bestaat het vermoeden, dat Studio Brussel per ongeluk vergeten was om de stemmen voor de verschillende versies samen te tellen. Het is ook al twee keer gebeurd dat eenzelfde nummer twee keer in de lijst stond, waarvan een keer met een verkeerde artiest. [Something] stond in 2023 zowel voor [The Beatles] (correct) als voor [George Harrison] (schrijver en zanger van het nummer, maar niet de officiële artiest) in de countdown. En [Are 'Friends' Electric?] stond in 2024 zowel als van [Tubeway Army] (correct) als van [Gary Numan] (lead-zanger maar niet de officiële artiest van dit nummer) in de lijst. In de database van tijdloze.rocks zijn deze nummers enkel aan de correcte artiest gekoppeld.")
</template>
