<template lang="pug">
p De Tijdloze werd altijd al gedomineerd door mannen. Misschien wel daarom is er ook altijd al speciale aandacht geweest voor het kleinere aantal vrouwen in de Tijdloze. In 2018 was er zelfs een grootschalige campagne om meer vrouwen in de top 100 te krijgen.
p
  make-links(text="Maar hoe tel je nu het aantal vrouwen en mannen in de Tijdloze? De band [Massive Attack] bijvoorbeeld bestaat alleen maar uit mannen, maar hun bekendste nummer [Unfinished Sympathy] heeft wel een tekst die door een vrouw is gezongen. Daarom leek het ons logischer om niet naar de geslachten van alle bandleden te kijken, maar wel naar de <em>lead vocals</em> van elk nummer. We hebben hierbij vier categoriën gedefinieerd: <em>man</em>, <em>vrouw</em>, <em>duet</em> (voor nummers waarbij mannelijke en vrouwelijke stemmen een min of meer evenwaardige rol spelen) en <em>instrumentaal</em>. Dit is natuurlijk een abstractie, en niet elk nummer past even goed in deze categorieën. Een voorbeeld waar dit waarschijnlijk tamelijk gevoelig ligt, is [K's Choice]. Het lijkt ons het meest logisch om nummers zoals [Not an Addict] nog bij de vrouwelijke lead vocals te tellen, ook al gaat zanger Sam Bettens (vroeger gekend als Sarah Bettens) tegenwoordig door het leven als man. Een gelijkaardig geval vinden we ook bij [Christine and the Queens].")
p
  make-links(text="De lead vocals zijn dus een eigenschap van elk nummer, en die is niet altijd hetzelfde voor de nummers van eenzelfde artist. Zo heeft [Fleetwoord Mac] bijvoorbeeld nummers in alle vier categorieën: <em>man</em> (bijvoorbeeld [Go Your Own Way]), <em>vrouw</em> (bijvoorbeeld [Dreams]), <em>duet</em> (bijvoorbeeld [The Chain]) en instrumentaal ([Albatross]).")
p
  make-links(text="Er zijn twee opvallende nummers in de databank waarbij de taal als <em>instrumentaal</em> is gedefinieerd, maar de lead vocals niet. [Hocus Pocus] van [Focus] heeft geen tekst, maar er wordt toch gezongen door een mannelijke stem. En [The Great Gig in the Sky] van [Pink Floyd] heeft weliswaar een korte Engelstalige tekst die door een man wordt gesproken, maar het nummer wordt gedomineerd door woordenloos vrouwelijk gezang.")
</template>
